/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ifTable.h"



    /* Typical data structure for a row entry */
struct ifTable_entry {
    /* Index values */
    long ifIndex;
    /* Illustrate using a simple linked list */
    int   valid;
    struct ifTable_entry *next;
};

struct ifTable_entry  *ifTable_head;

/* create a new row in the (unsorted) table */
struct ifTable_entry *
ifTable_createEntry(
                 long  ifIndex
                ) {
    struct ifTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct ifTable_entry);
    if (!entry)
        return NULL;

    entry->ifIndex = ifIndex;
    entry->next = ifTable_head;
    ifTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
ifTable_removeEntry( struct ifTable_entry *entry ) {
    struct ifTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = ifTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        ifTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}

static int count = 0;

/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
ifTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = ifTable_head;
    printf("times: %d\n", count++);
    return ifTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
ifTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct ifTable_entry *entry = (struct ifTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->ifIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** Initializes the ifTable module */
void
init_ifTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_ifTable();
}

/** Initialize the ifTable table by defining its contents and how it's structured */
void
initialize_table_ifTable(void)
{
    const oid ifTable_oid[] = {1,3,6,1,2,1,2,2};
    const size_t ifTable_oid_len   = OID_LENGTH(ifTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("ifTable:init", "initializing table ifTable\n"));

    reg = netsnmp_create_handler_registration(
              "ifTable",     ifTable_handler,
              ifTable_oid, ifTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: ifIndex */
                           0);
    table_info->min_column = COLUMN_IFINDEX;
    table_info->max_column = COLUMN_IFSPECIFIC;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = ifTable_get_first_data_point;
    iinfo->get_next_data_point  = ifTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    ifTable_createEntry(0);
    ifTable_createEntry(1);
}

/** handles requests for the ifTable table */
int
ifTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct ifTable_entry          *table_entry;

    DEBUGMSGTL(("ifTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct ifTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_IFINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ifIndex);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
